# Multi-stage build for auth-service
FROM node:20-alpine3.18 AS builder

# Set working directory
WORKDIR /app

# Copy shared folder first
COPY shared ./shared

# Copy auth-service package files
COPY services/auth-service/package*.json ./services/auth-service/

# Install dependencies for auth-service
WORKDIR /app/services/auth-service
RUN npm install

# Copy auth-service source code
COPY services/auth-service/tsconfig.json ./
COPY services/auth-service/prisma ./prisma
COPY services/auth-service/src ./src

# Build the application
RUN npm run build

# Production stage
FROM node:20-alpine3.18

# Create app user
RUN addgroup app && adduser -S -G app app

# Set working directory
WORKDIR /app

# Copy package files
COPY --chown=app:app services/auth-service/package*.json ./

# Install only production dependencies
RUN npm install --only=production

# Copy built application from builder stage
COPY --chown=app:app --from=builder /app/services/auth-service/dist ./dist
COPY --chown=app:app --from=builder /app/services/auth-service/prisma ./prisma

# Generate Prisma Client
RUN npx prisma generate

# Switch to app user
USER app

# Expose port
EXPOSE 3001

# Start the application
CMD ["npm", "start"]